server:
  port: 8871

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    hostname: 172.16.60.78
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: server-center
